# -*- coding: utf-8 -*-
"""timelapse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1al_jKT9rwdpz7s4haiM82TeJuLh7TVbG
"""

import cv2
import datetime

import os

folder= "Timelapse_Pictures"
#path = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Pictures')

path = os.getcwd()

path = path + "\\" + folder

if os.path.isdir(path):
    # directory exists
    path = path
else:
    os.mkdir(path)
print(path)
webcam = cv2.VideoCapture(0)

ret, frame = webcam.read()
if ret:
    timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    image_path = f"{path}\\image_{timestamp}.jpg"
    cv2.imwrite(image_path, frame)

